import type { Album, Track } from './types';

export const MOCK_ALBUMS: Album[] = [
  {
    id: 'album-001',
    AlbumTitle: 'Nevermind',
    AlbumArtist: 'Nirvana',
    ReleaseDate: '1991-09-24',
    RecordLabel: 'DGC Records',
    CatalogNumber: 'DGC-24425',
    EditionType: 'Standard',
    DiscCount: '1',
    TrackTotal: '12',
    AlbumGenre: 'Rock',
    AlbumMood: 'Energetic',
  },
  {
    id: 'album-002',
    AlbumTitle: 'Kind of Blue',
    AlbumArtist: 'Miles Davis',
    ReleaseDate: '1959-08-17',
    RecordLabel: 'Columbia Records',
    CatalogNumber: 'CL-1355',
    EditionType: 'Standard',
    DiscCount: '1',
    TrackTotal: '5',
    AlbumGenre: 'Jazz',
    AlbumMood: 'Calm',
  },
  {
    id: 'album-003',
    AlbumTitle: 'Thriller',
    AlbumArtist: 'Michael Jackson',
    ReleaseDate: '1982-11-30',
    RecordLabel: 'Epic Records',
    CatalogNumber: 'QE-38112',
    EditionType: 'Standard',
    DiscCount: '1',
    TrackTotal: '9',
    AlbumGenre: 'Pop',
    AlbumMood: 'Energetic',
  },
];

export const MOCK_TRACKS: Track[] = [
  {
    id: 'track-001',
    TrackTitle: 'Smells Like Teen Spirit',
    PrimaryArtist: 'Nirvana',
    FeaturedArtists: '',
    AlbumName: 'Nevermind',
    ReleaseYear: '1991',
    GenreCluster: 'Rock',
    MoodSignature: 'Energetic',
    TempoBPM: '117',
    EnergyLevel: '',
    ExplicitContentFlag: 'Clean',
    ProducerCredits: 'Butch Vig',
    ComposerList: 'Kurt Cobain',
    MasteringEngineer: '',
    RecordingLocation: '',
    ISRCCode: 'US-DGC-91-00001',
    CoverArtPalette: '',
    PlaybackGain: '',
    ListenerAtmosphere: '',
    GeoOrigin: '',
    StreamingPriority: '',
    WaveformFingerprint: '',
    LyricLanguage: 'English',
    VocalStyle: 'Grunge',
    CopyrightHolder: 'DGC Records',
    AIGenerationRatio: '0',
  },
  {
    id: 'track-002',
    TrackTitle: 'Come as You Are',
    PrimaryArtist: 'Nirvana',
    FeaturedArtists: '',
    AlbumName: 'Nevermind',
    ReleaseYear: '1991',
    GenreCluster: 'Rock',
    MoodSignature: 'Dark',
    TempoBPM: '120',
    EnergyLevel: '',
    ExplicitContentFlag: 'Clean',
    ProducerCredits: 'Butch Vig',
    ComposerList: 'Kurt Cobain',
    MasteringEngineer: '',
    RecordingLocation: '',
    ISRCCode: 'US-DGC-91-00002',
    CoverArtPalette: '',
    PlaybackGain: '',
    ListenerAtmosphere: '',
    GeoOrigin: '',
    StreamingPriority: '',
    WaveformFingerprint: '',
    LyricLanguage: 'English',
    VocalStyle: 'Grunge',
    CopyrightHolder: 'DGC Records',
    AIGenerationRatio: '0',
  },
  {
    id: 'track-003',
    TrackTitle: 'So What',
    PrimaryArtist: 'Miles Davis',
    FeaturedArtists: '',
    AlbumName: 'Kind of Blue',
    ReleaseYear: '1959',
    GenreCluster: 'Jazz',
    MoodSignature: 'Calm',
    TempoBPM: '136',
    EnergyLevel: '',
    ExplicitContentFlag: 'Clean',
    ProducerCredits: 'Teo Macero',
    ComposerList: 'Miles Davis',
    MasteringEngineer: '',
    RecordingLocation: '',
    ISRCCode: 'US-COL-59-00001',
    CoverArtPalette: '',
    PlaybackGain: '',
    ListenerAtmosphere: '',
    GeoOrigin: '',
    StreamingPriority: '',
    WaveformFingerprint: '',
    LyricLanguage: 'Instrumental',
    VocalStyle: 'Instrumental',
    CopyrightHolder: 'Columbia Records',
    AIGenerationRatio: '0',
  },
  {
    id: 'track-004',
    TrackTitle: 'Blue in Green',
    PrimaryArtist: 'Miles Davis',
    FeaturedArtists: '',
    AlbumName: 'Kind of Blue',
    ReleaseYear: '1959',
    GenreCluster: 'Jazz',
    MoodSignature: 'Melancholic',
    TempoBPM: '64',
    EnergyLevel: '',
    ExplicitContentFlag: 'Clean',
    ProducerCredits: 'Teo Macero',
    ComposerList: 'Bill Evans',
    MasteringEngineer: '',
    RecordingLocation: '',
    ISRCCode: 'US-COL-59-00002',
    CoverArtPalette: '',
    PlaybackGain: '',
    ListenerAtmosphere: '',
    GeoOrigin: '',
    StreamingPriority: '',
    WaveformFingerprint: '',
    LyricLanguage: 'Instrumental',
    VocalStyle: 'Instrumental',
    CopyrightHolder: 'Columbia Records',
    AIGenerationRatio: '0',
  },
  {
    id: 'track-005',
    TrackTitle: 'Billie Jean',
    PrimaryArtist: 'Michael Jackson',
    FeaturedArtists: '',
    AlbumName: 'Thriller',
    ReleaseYear: '1982',
    GenreCluster: 'Pop',
    MoodSignature: 'Energetic',
    TempoBPM: '117',
    EnergyLevel: '',
    ExplicitContentFlag: 'Clean',
    ProducerCredits: 'Quincy Jones',
    ComposerList: 'Michael Jackson',
    MasteringEngineer: '',
    RecordingLocation: '',
    ISRCCode: 'US-EPC-82-00001',
    CoverArtPalette: '',
    PlaybackGain: '',
    ListenerAtmosphere: '',
    GeoOrigin: '',
    StreamingPriority: '',
    WaveformFingerprint: '',
    LyricLanguage: 'English',
    VocalStyle: 'Pop',
    CopyrightHolder: 'Epic Records',
    AIGenerationRatio: '0',
  },
];
